# Generated by Django 5.2.4 on 2025-07-19 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocioComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Socio')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso al Convenio')),
                ('ciudad_sede', models.CharField(max_length=100, verbose_name='Ciudad de la Sede')),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Documento del Contrato')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Socio Comercial',
                'verbose_name_plural': 'Socios Comerciales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
