# Generated by Django 5.2.4 on 2025-07-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociocomercial',
            name='asesor_asignado',
            field=models.CharField(blank=True, help_text='Nombre del asesor que atendió este socio comercial', max_length=200, verbose_name='Asesor Asignado'),
        ),
    ]
