# Generated by Django 5.2.4 on 2025-07-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio_potencial', models.CharField(max_length=200, verbose_name='Nombre del Socio Potencial')),
                ('presentacion_negocio', models.BooleanField(default=False, verbose_name='Presentación de Negocio Realizada')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación')),
                ('documentos_enviados', models.BooleanField(default=False, verbose_name='Documentos Enviados')),
                ('fecha_envio_documentos', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío de Documentos')),
                ('contrato_enviado', models.BooleanField(default=False, verbose_name='Contrato Enviado')),
                ('fecha_envio_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío de Contrato')),
                ('contrato_firmado', models.BooleanField(default=False, verbose_name='Contrato Firmado')),
                ('fecha_firma_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma de Contrato')),
                ('capacitacion_realizada', models.BooleanField(default=False, verbose_name='Capacitación Realizada')),
                ('fecha_capacitacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Capacitación')),
                ('usuario_creado', models.BooleanField(default=False, verbose_name='Usuario Creado')),
                ('fecha_creacion_usuario', models.DateField(blank=True, null=True, verbose_name='Fecha de Creación de Usuario')),
                ('proceso_completo', models.BooleanField(default=False, verbose_name='Proceso Completo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('socio_comercial', models.ForeignKey(blank=True, help_text='Se asociará automáticamente cuando el socio potencial se convierta en socio comercial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.sociocomercial', verbose_name='Socio Comercial (Si ya se creó)')),
            ],
            options={
                'verbose_name': 'Seguimiento de Socio',
                'verbose_name_plural': 'Seguimiento de Socios',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
